.TH MIGRAINE 1 "October 2025" "Version v1.0.7-0.20251016133554-d60b2e598a77+dirty" "Migraine Manual"
.SH NAME
migraine, mgr \\- A CLI tool used to organize and automate complex workflows with templated commands
.SH SYNOPSIS
.B migraine
.RB [COMMAND]
.RB [FLAGS]
.PP
.B mgr
.RB [COMMAND]
.RB [FLAGS]
.SH DESCRIPTION
Migraine is a robust CLI tool used to organize and automate complex workflows with templated commands.
Users can define, store, and run sequences of shell commands efficiently, featuring variable substitution,
pre-flight checks, and discrete actions.
.SH COMMANDS
.TP
.B help [command]
Help about any command
.TP
.B run [workflow-name]
Execute a workflow by name
.TP
.B vars [subcommand]
Manage vault variables with scope flags
.RS
.TP
.B vars list
List all variables
.TP
.B vars get [key]
Get a variable by key
.TP
.B vars set [key] [value]
Set a variable with key and value
.TP
.B vars delete [key]
Delete a variable by key
.RE
.TP
.B workflow [subcommand]
Manage workflows
.RS
.TP
.B workflow list
List all workflows
.TP
.B workflow get [name]
Get a workflow by name
.TP
.B workflow create [name]
Create a new workflow
.TP
.B workflow delete [name]
Delete a workflow by name
.TP
.B workflow info [name]
Show detailed information about a workflow
.RE
.TP
.B version [flags]
Show version information
.RS
.TP
.B \\-\\-json
Output version information in JSON format
.TP
.B \\-s, \\-\\-short
Output short version only
.TP
.B \\-c, \\-\\-commit
Output version with commit hash
.RE
.TP
.B buildinfo
Show detailed build information
.TP
.B man
Display this manual page
.SH OPTIONS
.TP
.B \\-v, \\-\\-version
Print detailed version information
.SH EXAMPLES
.TP
.B $ migraine run my-workflow
Run a workflow
.TP
.B $ migraine workflow list
List all workflows
.TP
.B $ migraine vars set API_KEY mysecretkey
Set a variable
.TP
.B $ migraine version
Get version information
.SH AUTHOR
Tesh Teckie <tesh254@proton.me>
.SH COPYRIGHT
MIT License \\- Copyright (c) 2024\\-2025 Tesh Teckie
