package editor

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

var supportedEditors = []string{"vscode", "neovim", "vim", "helix"}

func Supported() []string {
	return supportedEditors
}

func Detect() []string {
	var found []string
	if _, err := exec.LookPath("code"); err == nil {
		found = append(found, "vscode")
	}
	if _, err := exec.LookPath("nvim"); err == nil {
		found = append(found, "neovim")
	}
	if _, err := exec.LookPath("vim"); err == nil {
		found = append(found, "vim")
	}
	if _, err := exec.LookPath("hx"); err == nil {
		found = append(found, "helix")
	}
	return found
}

func Setup(editor, migrainePath string) error {
	if migrainePath == "" {
		var err error
		migrainePath, err = exec.LookPath("migraine")
		if err != nil {
			return fmt.Errorf("migraine binary not found on PATH")
		}
	}

	switch editor {
	case "vscode":
		return setupVSCode()
	case "neovim", "nvim":
		return setupNeovim(migrainePath)
	case "vim":
		return setupVim(migrainePath)
	case "helix":
		return setupHelix(migrainePath)
	default:
		return fmt.Errorf("unsupported editor: %s (supported: %s)", editor, strings.Join(supportedEditors, ", "))
	}
}

func setupVSCode() error {
	codePath, _ := exec.LookPath("code")

	vsixPath := findVsix()
	if vsixPath == "" {
		return fmt.Errorf("could not find .vsix extension — run 'cd editors/vscode && npx @vscode/vsce package --no-dependencies' to build it")
	}

	cmd := exec.Command(codePath, "--install-extension", vsixPath)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("code --install-extension failed: %s", strings.TrimSpace(string(out)))
	}
	return nil
}

func findVsix() string {
	exePath, err := os.Executable()
	if err != nil {
		return ""
	}
	dir := filepath.Dir(exePath)
	candidates := []string{
		filepath.Join(dir, "editors", "vscode", "migraine-lsp-0.1.0.vsix"),
		filepath.Join(dir, "..", "editors", "vscode", "migraine-lsp-0.1.0.vsix"),
	}
	for _, c := range candidates {
		if _, err := os.Stat(c); err == nil {
			return c
		}
	}
	return ""
}

func setupNeovim(migrainePath string) error {
	configDir := nvimConfigDir()
	if err := os.MkdirAll(filepath.Join(configDir, "lua"), 0o755); err != nil {
		return fmt.Errorf("create nvim lua dir: %w", err)
	}

	luaContent := fmt.Sprintf(`-- Migraine LSP (auto-generated by 'migraine init --editor neovim')
-- Add to your init.lua: require('migraine_lsp').setup()

local lspconfig = require('lspconfig')

local M = {}

M.setup = function(opts)
  opts = opts or {}
  lspconfig.migraine_lsp.setup({
    cmd = { '%s', 'lsp' },
    filetypes = { 'migraine' },
    root_dir = lspconfig.util.find_git_ancestor,
    capabilities = opts.capabilities,
    on_attach = opts.on_attach,
  })
end

return M
`, migrainePath)

	if err := os.WriteFile(filepath.Join(configDir, "lua", "migraine_lsp.lua"), []byte(luaContent), 0o644); err != nil {
		return fmt.Errorf("write lspconfig: %w", err)
	}

	ftdetectDir := filepath.Join(configDir, "ftdetect")
	if err := os.MkdirAll(ftdetectDir, 0o755); err != nil {
		return fmt.Errorf("create ftdetect dir: %w", err)
	}
	if err := os.WriteFile(filepath.Join(ftdetectDir, "migraine.lua"), []byte("vim.filetype.add({ extension = { mg = 'migraine' } })\n"), 0o644); err != nil {
		return fmt.Errorf("write ftdetect: %w", err)
	}

	syntaxDir := filepath.Join(configDir, "syntax")
	if err := os.MkdirAll(syntaxDir, 0o755); err != nil {
		return fmt.Errorf("create syntax dir: %w", err)
	}
	syntaxContent := strings.Join([]string{
		`" Migraine syntax (auto-generated by 'migraine init --editor neovim')`,
		`syn keyword migraineBlock metadata variables workflow config`,
		`syn keyword migraineSection pre_checks steps actions`,
		`syn keyword migraineProperty cmd desc description name on_fail on_success`,
		`syn keyword migraineProperty store_variables store_logs background global`,
		`syn keyword migraineBool true false`,
		``,
		`syn match migraineComment "#.*$"`,
		`syn match migrainePrefix "\\v<(args|env|vault|action):[A-Za-z_][A-Za-z0-9_]*"`,
		`syn match migrainePrefix "\\v<run:"`,
		`syn match migraineTemplate "{{[^}]*}}"`,
		`syn match migraineAssign "="`,
		``,
		`syn region migraineString start=+"+ skip=+\\\\\|\\"+ end=+"+ contains=migraineTemplate`,
		"syn region migraineRawString start=+`+ end=+`+ contains=migraineTemplate",
		``,
		`hi def link migraineBlock Keyword`,
		`hi def link migraineSection Keyword`,
		`hi def link migraineProperty Identifier`,
		`hi def link migraineBool Boolean`,
		`hi def link migraineComment Comment`,
		`hi def link migrainePrefix Special`,
		`hi def link migraineTemplate PreProc`,
		`hi def link migraineString String`,
		`hi def link migraineRawString String`,
		`hi def link migraineAssign Operator`,
		``,
		`let b:current_syntax = 'migraine'`,
	}, "\n") + "\n"

	if err := os.WriteFile(filepath.Join(syntaxDir, "migraine.vim"), []byte(syntaxContent), 0o644); err != nil {
		return fmt.Errorf("write syntax: %w", err)
	}

	fmt.Printf("  Neovim config written to %s\n", configDir)
	fmt.Println("  Add this to your init.lua: require('migraine_lsp').setup()")
	return nil
}

func setupVim(migrainePath string) error {
	vimDir := vimConfigDir()

	ftdetectDir := filepath.Join(vimDir, "ftdetect")
	if err := os.MkdirAll(ftdetectDir, 0o755); err != nil {
		return fmt.Errorf("create ftdetect dir: %w", err)
	}
	if err := os.WriteFile(filepath.Join(ftdetectDir, "migraine.vim"), []byte("autocmd BufRead,BufNewFile *.mg set filetype=migraine\n"), 0o644); err != nil {
		return fmt.Errorf("write ftdetect: %w", err)
	}

	syntaxDir := filepath.Join(vimDir, "syntax")
	if err := os.MkdirAll(syntaxDir, 0o755); err != nil {
		return fmt.Errorf("create syntax dir: %w", err)
	}
	syntaxContent := strings.Join([]string{
		`" Migraine syntax (auto-generated by 'migraine init --editor vim')`,
		`syn keyword migraineBlock metadata variables workflow config`,
		`syn keyword migraineSection pre_checks steps actions`,
		`syn keyword migraineProperty cmd desc description name on_fail on_success`,
		`syn keyword migraineProperty store_variables store_logs background global`,
		`syn keyword migraineBool true false`,
		``,
		`syn match migraineComment "#.*$"`,
		`syn match migrainePrefix "\\v<(args|env|vault|action):[A-Za-z_][A-Za-z0-9_]*"`,
		`syn match migrainePrefix "\\v<run:"`,
		`syn match migraineTemplate "{{[^}]*}}"`,
		`syn match migraineAssign "="`,
		``,
		`syn region migraineString start=+"+ skip=+\\\\\|\\"+ end=+"+ contains=migraineTemplate`,
		"syn region migraineRawString start=+`+ end=+`+ contains=migraineTemplate",
		``,
		`hi def link migraineBlock Keyword`,
		`hi def link migraineSection Keyword`,
		`hi def link migraineProperty Identifier`,
		`hi def link migraineBool Boolean`,
		`hi def link migraineComment Comment`,
		`hi def link migrainePrefix Special`,
		`hi def link migraineTemplate PreProc`,
		`hi def link migraineString String`,
		`hi def link migraineRawString String`,
		`hi def link migraineAssign Operator`,
		``,
		`let b:current_syntax = 'migraine'`,
	}, "\n") + "\n"

	if err := os.WriteFile(filepath.Join(syntaxDir, "migraine.vim"), []byte(syntaxContent), 0o644); err != nil {
		return fmt.Errorf("write syntax: %w", err)
	}

	fmt.Printf("  Vim config written to %s\n", vimDir)
	return nil
}

func setupHelix(migrainePath string) error {
	configDir := helixConfigDir()
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		return fmt.Errorf("create helix config dir: %w", err)
	}

	languagesFile := filepath.Join(configDir, "languages.toml")

	entry := fmt.Sprintf("\n# Migraine LSP (auto-generated by 'migraine init --editor helix')\n[[language]]\nname = \"migraine\"\nscope = \"source.mg\"\nfile-types = [\"mg\"]\nroots = [\"migraine.yaml\"]\ncomment-token = \"#\"\n\n[language-server.migraine-lsp]\ncommand = \"%s\"\nargs = [\"lsp\"]\n", migrainePath)

	var existing []byte
	if data, err := os.ReadFile(languagesFile); err == nil {
		existing = data
	}

	content := string(existing) + entry
	if err := os.WriteFile(languagesFile, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write helix languages.toml: %w", err)
	}

	fmt.Printf("  Helix config written to %s\n", languagesFile)
	return nil
}

func nvimConfigDir() string {
	home, _ := os.UserHomeDir()
	if xdg := os.Getenv("XDG_CONFIG_HOME"); xdg != "" {
		return filepath.Join(xdg, "nvim")
	}
	return filepath.Join(home, ".config", "nvim")
}

func vimConfigDir() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".vim")
}

func helixConfigDir() string {
	home, _ := os.UserHomeDir()
	if runtime.GOOS == "darwin" {
		return filepath.Join(home, "Library", "Preferences", "helix")
	}
	xdg := os.Getenv("XDG_CONFIG_HOME")
	if xdg != "" {
		return filepath.Join(xdg, "helix")
	}
	return filepath.Join(home, ".config", "helix")
}